
- name: "Include OS-specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Ensure helper applications
  package:
    name: curl

- name: Create {{ zabbix_server_mit_snmpget_path }}
  file:
    dest: "{{ zabbix_server_mit_snmpget_path }}"
    state: directory
    owner: zabbix
    group: zabbix
    mode: 0750

- name: Copy scripts to {{ zabbix_server_externalscripts_path }}
  template:
    src: "{{ item }}"
    dest: "{{ zabbix_server_externalscripts_path }}"
    mode: "0755"
  loop:
    - check-ssl-tls.sh
    - check-ssl-tls-sni.sh
    - mit-get-http-header.sh
    - mit-snmpget
    - mit-snmpget3
    - mit-zabbix-executor

- name: Check depreated (1/2)
  ansible.builtin.stat:
    path: "{{ zabbix_server_mit_snmpget_path_deprecated }}"
  register: st

- name: Check depreated (2/2)
  ansible.builtin.fail:
    msg: "Please remove {{ zabbix_server_mit_snmpget_path_deprecated }}, it has been replaced by {{ zabbix_server_mit_snmpget_path }}"
  when: st.stat.exists

