---

# mit-zabbix-set-pkg-name-prefix - 5, 6, 64, 7

- name: Set zabbix_server_pkg_name_prefix (1/2)
  ansible.builtin.set_fact:
    zabbix_server_pkg_name_prefix: zabbix{{ zabbix_server_version | regex_replace('^([0-9]+)\.([0-9]+.*)$', '\1') }}
- name: Set zabbix_server_pkg_name_prefix (2/2)
  ansible.builtin.set_fact:
    zabbix_server_pkg_name_prefix: zabbix{{ zabbix_server_version | regex_replace('^([0-9]+)\.([0-9]+)(.*)$', '\1\2') }}
  when: zabbix_server_version is regex('^6\.4\..*')

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

# coreutils is needed on FreeBSD to provide gdate
- name: Ensure helper applications
  ansible.builtin.package:
    name:
      - coreutils
      - curl

- name: Create {{ zabbix_server_mit_snmpget_path }}
  ansible.builtin.file:
    dest: "{{ zabbix_server_mit_snmpget_path }}"
    state: directory
    owner: zabbix
    group: zabbix
    mode: "0750"

- name: Copy scripts to {{ zabbix_server_externalscripts_path }}
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ zabbix_server_externalscripts_path }}"
    mode: "0755"
  loop:
    - check-ssl-tls.sh
    - check-ssl-tls-sni.sh
    - mit-get-http-header.sh
    - mit-snmpget
    - mit-snmpget3
    - mit-zabbix-executor

- name: Check depreated (1/2)
  ansible.builtin.stat:
    path: "{{ zabbix_server_mit_snmpget_path_deprecated }}"
  register: st

- name: Check depreated (2/2)
  ansible.builtin.fail:
    msg: Please remove {{ zabbix_server_mit_snmpget_path_deprecated }}, it has been replaced by {{ zabbix_server_mit_snmpget_path }}
  when: st.stat.exists
